### PR TITLE
Add support for BladeRF in srslte

### PR DESCRIPTION
**Pull request by platini2**
Compile BladeRF and Soapy BladeRF from source

### CODE REVIEW

**Comment by herlesupreeth** [comment]
Thanks for the PR. Have you tested whether srsRAN_4G works with BladeRF??

**Comment by platini2** [comment]
> Thanks for the PR. Have you tested whether srsRAN_4G works with BladeRF??

Yes it does, i am working on troubleshooting some power levels but compuiles and BladeRF comes up with this patch.


Deploying component: 'enb'
Active RF plugins: libsrsran_rf_uhd.so libsrsran_rf_soapy.so libsrsran_rf_blade.so libsrsran_rf_zmq.so
Inactive RF plugins: 
---  Software Radio Systems LTE eNodeB  ---

Couldn't open , trying /root/.config/srsran/enb.conf
Couldn't open /root/.config/srsran/enb.conf either, trying /etc/srsran/enb.conf
Reading configuration file /etc/srsran/enb.conf...

Built in Release mode using commit 4eb990c9c on branch HEAD.

Opening 1 channels in RF device=soapy with args=default
Supported RF device list: UHD soapy bladeRF zmq file
Soapy has found device #0: backend=libusb, device=0x04:0x02, driver=bladerf, instance=0, label=BladeRF #0 [], serial=, 
Selecting Soapy device: 0
[INFO] bladerf_open_with_devinfo()
[INFO] bladerf_get_serial() = 2eb81b02ddcd454e93ea131d19b8a948
[INFO] setSampleRate(Rx, 0, 4.000000 MHz), actual = 4.000000 MHz
[INFO] setSampleRate(Tx, 0, 4.000000 MHz), actual = 4.000000 MHz
Setting up Rx stream with 1 channel(s)
Setting up Tx stream with 1 channel(s)
[INFO] setSampleRate(Rx, 0, 1.920000 MHz), actual = 1.920000 MHz
[INFO] setSampleRate(Tx, 0, 1.920000 MHz), actual = 1.920000 MHz
Available device sensors: 
 - RFIC_TEMP
Available sensors for Rx channel 0: 
 - PRE_RSSI
 - SYM_RSSI
State of gain elements for Rx channel 0 (AGC supported):
 - full: 69.00 dB
State of gain elements for Tx channel 0 (AGC not supported):
 - dsa: -10.00 dB
Rx antenna set to RX
Tx antenna set to TX

==== eNodeB started ===
Type <t> to view trace
[INFO] setSampleRate(Rx, 0, 3.840000 MHz), actual = 3.840000 MHz
[INFO] setSampleRate(Tx, 0, 3.840000 MHz), actual = 3.840000 MHz
Setting frequency: DL=2115.0 Mhz, UL=1925.0 MHz for cc_idx=0 nof_prb=15
000000
t
Enter t to stop trace.
0RF status: O=1, U=0, L=0
0RF status: O=1, U=0, L=0
00RF status: O=2, U=0, L=0
0RF status: O=1, U=0, L=0

**Comment by herlesupreeth** [comment]
Ah, nice..thanks again

**Comment by platini2** [comment]
> Ah, nice..thanks again

Confirmed to work, iphone 14 and google pixel came up in a band 5 configuration with 25 prb in a raspberry pi 5 with bladeRF

**Pull request merged**
