### PR TITLE
Add github action to build image and upload to ghcr.io

### PR DESCRIPTION
**Pull request by FlyGoat**
Images will be built automatically and uploaded to `ghcr.io` so people don't need to build locally.

It would look like: https://github.com/FlyGoat?tab=packages&repo_name=docker_open5gs

### CODE REVIEW

**Comment by herlesupreeth** [comment]
Thats cool. I am not quite familiar with github actions. So if I understood it right, whenever I push a commit to master, the image gets built automatically and uploaded??

**Comment by FlyGoat** [comment]
> Thats cool. I am not quite familiar with github actions. So if I understood it right, whenever I push a commit to master, the image gets built automatically and uploaded??

Yes that’s correct, something like

https://github.com/FlyGoat/docker_open5gs/actions/runs/10539299779

Would be performed for every push.

Also for pull_request build test will be performed but artifacts won’t be published to the registry.

Thanks

**Comment by herlesupreeth** [comment]
Thank you for your contribution

**Comment by herlesupreeth** [comment]
Sorry, one last question, if I push changes to any other branch than master would the github action compile image??

**Comment by FlyGoat** [comment]
> Sorry, one last question, if I push changes to any other branch than master would the github action compile image??

It will I think, the image will be tagged with branch name.

**Comment by FlyGoat** [comment]
I don't really know why https://github.com/herlesupreeth/docker_open5gs/actions/runs/10596034473 failed, looks like a GitHub glitch.

Will try to update README.md about ghcr.io prebuilt image usage if things work out.

**Comment by herlesupreeth** [comment]
Could it be due me not having a PRO github account and the quota for image size is reached??

**Pull request merged**
